service:
    id: prv
    version: 1.0.0
dubbo:
    application:
        id: dubbo-provider-demo
        name: dubbo-provider-demo
    protocol:
        id: zookeeper
        name: dubbo
        port: 20081
        status: server
        threads: 10
    registry:
        address: 127.0.0.1:2181
        id: my-registry
        protocol: zookeeper
        timeout: 30000
    scan:
        basePackages: com.lzy.dubboprovider.server
server:
    port: 8092
spring:
    application:
        name: dubbo-provider-demo
    profiles:
        include: mybatis
    redis:
        database: 0
        host: localhost
        jedis:
            pool:
                max-active: 200
                max-idle: 10
                max-wait: -1
                min-idle: 0
        password: ''
        port: 6379
        timeout: 1000
logging:
  level: {
  com.lzy.dubboprovider: "debug"
  }