demo:
    service:
        version: 1.0.0
dubbo:
    application:
        id: dubbo-controller-demo
        name: dubbo-controller-demo
    protocol:
        id: dubbo
        name: dubbo
        port: 20080
        threads: 10
    registry:
        address: 127.0.0.1:2181
        id: my-registry1
        protocol: zookeeper
        timeout: 30000
management:
    server:
        port: 8091
server:
    port: 8090
spring:
    application:
        name: dubbo-controller-demo
    redis:
        database: 0
        host: localhost
        jedis:
            pool:
                max-active: 200
                max-idle: 10
                max-wait: -1
                min-idle: 0
        password: ''
        port: 6379
        timeout: 1000
    mvc:
        dispatch-options-request: true
logging:
  level: {
  com.lzy.consumer: "debug"
  }